"""
BH-12 GeoTIFF Writer
=====================
Rewrites the synthetic Kayad example TIFs as proper GeoTIFFs with:
  - EPSG:32643 (WGS 84 / UTM Zone 43N) CRS embedded via GeoKeyDirectory
  - ModelPixelScale + ModelTiepoint geotransform
  - Standard north-to-south row order (row 0 = northernmost pixel)
  - Float32 pixel values (mGal for gravity, uSI for magnetics)

No external dependencies beyond numpy + Pillow (both ship with QGIS).

Standard GeoTIFF orientation (north-up, row 0 = north) requires flipping
the arrays that were generated south-to-north. The DataLoader._load_tif_folder
reads this correctly when using the GDAL backend (the gt[5] < 0 check added
in the same commit as this script causes it to flip back to south-to-north
to match the scoring-engine cell ordering).

Run:
    python write_geotiffs_bh12.py
from the kayad_synthetic directory.
"""
import os
import struct
import numpy as np
from PIL import Image


# ── Minimal GeoTIFF writer (no GDAL/rasterio required) ───────────────────────

def write_geotiff_float32(arr_south_up: np.ndarray, path: str,
                           xmin: float, ymin: float,
                           dx: float, dy: float,
                           epsg: int) -> None:
    """
    Write a 2D float32 numpy array as a GeoTIFF.

    arr_south_up : 2D array with row 0 = SOUTH (as generated by meshgrid
                   matching VoxelBuilder cell_N ordering).
                   This function flips it to standard north-up (row 0 = north)
                   for the file on disk.
    xmin, ymin   : SW corner coordinates (metres, projected)
    dx, dy       : positive pixel size in x and y (metres)
    epsg         : EPSG code for the projected CRS (e.g. 32643)
    """
    # Flip to north-up for standard GeoTIFF orientation
    arr = np.flipud(arr_south_up).astype(np.float32)
    ny, nx = arr.shape

    # Top-left corner = NW corner (row 0 = northernmost)
    ymax = ymin + ny * dy

    # ── Binary layout (classic TIFF, little-endian) ──────────────────────────
    # [0..7]    : TIFF header
    # [8..181]  : IFD (2 + 14*12 + 4 = 174 bytes)
    # [182..205]: ModelPixelScale  (3 doubles = 24 bytes)
    # [206..253]: ModelTiepoint    (6 doubles = 48 bytes)
    # [254..285]: GeoKeyDirectory  (16 shorts = 32 bytes)
    # [286+]    : image data       (nx*ny*4 bytes)

    N_TAGS       = 14
    IFD_OFFSET   = 8
    IFD_SIZE     = 2 + N_TAGS * 12 + 4   # 174 bytes
    EXTRA_START  = IFD_OFFSET + IFD_SIZE  # 182
    PS_OFFSET    = EXTRA_START            # ModelPixelScale at 182
    TP_OFFSET    = PS_OFFSET  + 24        # ModelTiepoint   at 206
    GK_OFFSET    = TP_OFFSET  + 48        # GeoKeyDir       at 254
    DATA_OFFSET  = GK_OFFSET  + 32        # image data      at 286
    STRIP_BYTES  = nx * ny * 4

    def tag_long(tag, value):
        """12-byte IFD entry: tag value stored as LONG."""
        return struct.pack('<HHII', tag, 4, 1, int(value))

    def tag_short(tag, value):
        """12-byte IFD entry: tag value stored inline as SHORT + 2-byte pad."""
        return struct.pack('<HHI', tag, 3, 1) + struct.pack('<HH', int(value), 0)

    def tag_offset(tag, dtype, count, offset):
        """12-byte IFD entry pointing to extra data area."""
        return struct.pack('<HHII', tag, dtype, count, int(offset))

    # TIFF header: II (LE), magic 42, IFD at byte 8
    header = struct.pack('<2sHI', b'II', 42, IFD_OFFSET)

    # IFD entries (must be in ascending tag-number order)
    ifd  = struct.pack('<H', N_TAGS)
    ifd += tag_long (256, nx)           # ImageWidth
    ifd += tag_long (257, ny)           # ImageLength
    ifd += tag_short(258, 32)           # BitsPerSample  = 32
    ifd += tag_short(259, 1)            # Compression    = None
    ifd += tag_short(262, 1)            # PhotometricInterp = MinIsBlack
    ifd += tag_long (273, DATA_OFFSET)  # StripOffsets
    ifd += tag_short(277, 1)            # SamplesPerPixel = 1
    ifd += tag_long (278, ny)           # RowsPerStrip
    ifd += tag_long (279, STRIP_BYTES)  # StripByteCounts
    ifd += tag_short(284, 1)            # PlanarConfiguration = Contiguous
    ifd += tag_short(339, 3)            # SampleFormat = IEEE Float
    ifd += tag_offset(34264, 12, 3,  PS_OFFSET)  # ModelPixelScaleTag  (DOUBLE*3)
    ifd += tag_offset(34267, 12, 6,  TP_OFFSET)  # ModelTiepointTag    (DOUBLE*6)
    ifd += tag_offset(34735,  3, 16, GK_OFFSET)  # GeoKeyDirectoryTag  (SHORT*16)
    ifd += struct.pack('<I', 0)         # next IFD = 0 (no more IFDs)

    assert len(ifd) == IFD_SIZE, f"IFD size mismatch: {len(ifd)} != {IFD_SIZE}"

    # ModelPixelScale: [ScaleX, ScaleY, ScaleZ] — always positive
    pixscale = struct.pack('<3d', dx, dy, 0.0)

    # ModelTiepoint: [I, J, K, X, Y, Z]
    # Pixel (0,0) = top-left = NW corner = (xmin, ymax)
    tiepoint = struct.pack('<6d', 0.0, 0.0, 0.0, xmin, ymax, 0.0)

    # GeoKeyDirectory — EPSG:32643 (WGS 84 / UTM Zone 43N, Projected CRS)
    # Format: [KeyDirVersion, KeyRevision, MinorRevision, NumberOfKeys,
    #          KeyID, TIFFTagLocation, Count, Value/Offset, ...]
    geokeys = struct.pack('<16H',
        1, 1, 0, 3,          # Header: v1.1, 3 keys
        1024, 0, 1, 1,       # GTModelTypeGeoKey  = 1 (Projected)
        1025, 0, 1, 1,       # GTRasterTypeGeoKey = 1 (PixelIsArea)
        3072, 0, 1, epsg,    # ProjectedCRSGeoKey = EPSG code
    )

    with open(path, 'wb') as f:
        f.write(header)
        f.write(ifd)
        f.write(pixscale)
        f.write(tiepoint)
        f.write(geokeys)
        f.write(arr.tobytes())


# ── Read back PIL or previous TIF as float32 south-up array ──────────────────

def read_float_tif(path: str) -> np.ndarray:
    """
    Read a TIF file (PIL float32 or any TIFF) and return float32 array.
    Does NOT flip — assumes the file is already in the correct orientation
    for its intended use.
    """
    img = Image.open(path)
    return np.array(img, dtype=np.float32)


# ── MAIN ──────────────────────────────────────────────────────────────────────

XMIN  = 469490.0
YMIN  = 2934890.0
EPSG  = 32643
LEVELS = [270, 295, 320, 345, 370]
CS_G  = 5.0   # gravity pixel size (m)
CS_M  = 30.0  # magnetics pixel size (m)


def rewrite_folder(src_grav_dir, src_mag_dir, dst_grav_dir, dst_mag_dir,
                   label: str = '') -> None:
    """Read PIL TIFs from src, write proper GeoTIFFs to dst."""
    os.makedirs(dst_grav_dir, exist_ok=True)
    os.makedirs(dst_mag_dir,  exist_ok=True)

    print(f"\n{label}")
    for mrl in LEVELS:
        # Gravity
        g_src = os.path.join(src_grav_dir, f'grav_{mrl}.tif')
        g_dst = os.path.join(dst_grav_dir, f'grav_{mrl}.tif')
        arr_g = read_float_tif(g_src)   # south-up as generated
        write_geotiff_float32(arr_g, g_dst, XMIN, YMIN, CS_G, CS_G, EPSG)
        print(f"  grav_{mrl}.tif  {arr_g.shape}  "
              f"min={arr_g.min():.3f}  max={arr_g.max():.3f} mGal  -> {g_dst}")

        # Magnetics
        m_src = os.path.join(src_mag_dir, f'mag_{mrl}.tif')
        m_dst = os.path.join(dst_mag_dir, f'mag_{mrl}.tif')
        arr_m = read_float_tif(m_src)   # south-up as generated
        write_geotiff_float32(arr_m, m_dst, XMIN, YMIN, CS_M, CS_M, EPSG)
        print(f"  mag_{mrl}.tif   {arr_m.shape}  "
              f"min={arr_m.min():.2f}  max={arr_m.max():.2f} uSI  -> {m_dst}")


if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))

    SRC_GRAV = os.path.join(script_dir, 'geophysics', 'gravity')
    SRC_MAG  = os.path.join(script_dir, 'geophysics', 'magnetics')

    # 1. Rewrite plugin source TIFs in-place as proper GeoTIFFs
    rewrite_folder(
        SRC_GRAV, SRC_MAG,
        SRC_GRAV, SRC_MAG,
        label='Plugin source TIFs (in-place) -> EPSG:32643 GeoTIFF:',
    )

    # 2. Also write to project output folder
    DST_ROOT = (r'E:\MPXG Exploration Dropbox\amit tripathi'
                r'\2025Projects\P25013KayadLeadZinc-HZL-Rajasthan'
                r'\CAGE-IN\Bhumi3DmapperOutputs')
    DST_GRAV = os.path.join(DST_ROOT, 'geophysics', 'gravity')
    DST_MAG  = os.path.join(DST_ROOT, 'geophysics', 'magnetics')

    rewrite_folder(
        SRC_GRAV, SRC_MAG,
        DST_GRAV, DST_MAG,
        label='Project output folder -> EPSG:32643 GeoTIFF:',
    )

    print('\nDone. Verify in QGIS: right-click layer -> Properties -> CRS should show EPSG:32643.')
